apiVersion: v1
kind: Service
metadata:
  name: edu-animation-service
spec:
  type: NodePort
  selector:
    app: edu-animation
  ports:
    - port: 80
      targetPort: 80
      nodePort: 8088  # Expose on port 8088
