apiVersion: v1
kind: Service
metadata:
  name: edu-animation-service
spec:
  type: NodePort
  selector:
    app: edu-animation
  ports:
    - protocol: TCP
      port: 80         # Service port (inside the cluster)
      targetPort: 80    # Container port
      nodePort: 30080   # Valid node port in the range 30000-32767
